### ISSUE TITLE
Deprecate Harvest & Accounts sections

### ISSUE THREAD

**Issue by peacog** [Cambrico/tree_farmer#87]
The Harvest and Accounts sections should be deprecated, although each area/sub-area crop needs to be able to be retired through indicating it has been harvested, which then releases it for the establishment / creation of a new crop

**Comment by peacog** [comment]
Hi @LeScruf , @Rashids2021 

Can you clarify what is required here? 

- [ ] Should we remove harvest and accounts completely, including any existing data?
- [ ] What does it mean to _retire each area/sub-area crop through indicating it has been harvested_? We have an **Area Harvest** checkbox on sub areas. Is that what you mean? 

Removing the Harvest section would mean deleting the following:
- Thinning & harvest details
- Offtake type
- Unit
- Product type

Removing the Accounts section would mean deleting the following:
- Account detail
- Accounts simplification
- Annual charges
- Historical payments
- Charge (there are Charge records in the system. Do we need to keep them?)
- Fee payment - NFA
- Harvesting & miscellaneous fees
- Index / Zone annual rent charges
- Land rent rates
- Starting amount
- Payment
- Payment advice
- Fee
- Fee type

**Comment by LeScruf** [comment]
-- Should we remove harvest and accounts completely, including any existing data? 
-> Can these parts of the system be depreciated for now and hidden, just in case they need to be revived in the future?

-- What does it mean to retire each area/sub-area crop through indicating it has been harvested? We have an Area Harvest checkbox on sub areas. Is that what you mean? 
-> Yes - the check box should retire the area/sub-area but I think it would be good if retired sub-areas were viewable in a separate section (we need to look at how) - such that they can be 'unretired' if they have been retired by mistake, and also be available for subsequent review and analysis?

**Comment by peacog** [comment]
Hi @LeScruf . We will hide the harvest and accounts section but leave the backend in place.

As for retiring a sub-area. Do you mean that if the check box is ticked the sub-area will not appear in the Sub-areas tab on the farmer's page? An administrator would be able to retrieve it from the drupal content administration page and unretire it if it was done by mistake.

**Comment by LeScruf** [comment]
Hi, re para 2, yes correct. This then enables an entirely new sub-area to be created as needed to replace part or all of the retired sub-area. I guess then, in order to retrieve / reinstate the retired sub-area, one would first have to delete any new overlapping sub-area first. This means a rule / script will need to created to prevent overlapping areas being created / retrieved - if this is not already the case (if not this is something to add as a key functionality).

**Comment by peacog** [comment]
We don't currently have that functionality. We would have to compare the polygon against other existing polygons and warn or block if one already exists, correct?

**Comment by LeScruf** [comment]
Yes. Else we'll get all sorts of overlapping polygons...
