### ISSUE TITLE
Don't show most recent farmer before search

### ISSUE THREAD

**Issue by peacog** [Cambrico/tree_farmer#98]
The most recently added farmer is shown by default when you visit the farmer dashboard and before a search has been done. This should not happen

**Comment by peacog** [comment]
Closing this because it will be solved by Issue #82

**Comment by peacog** [comment]
This issue is solved in local dev environment but still occurs on production. Review when rebuilt server has been launched

**Comment by LeScruf** [comment]
Seems to be fixed now?
